create index academic_events_assessment_id_idx on public.academic_events (assessment_id);
create index academic_events_task_id_idx on public.academic_events (task_id);
create index academic_events_user_assessment_idx on public.academic_events (user_id, assessment_id);
create index academic_events_user_task_idx on public.academic_events (user_id, task_id);
create index academic_events_user_unit_idx on public.academic_events (user_id, unit_id);
create index assessments_user_unit_idx on public.assessments (user_id, unit_id);
create index observations_assessment_id_idx on public.observations (assessment_id);
create index observations_task_id_idx on public.observations (task_id);
create index observations_user_assessment_idx on public.observations (user_id, assessment_id);
create index observations_user_task_idx on public.observations (user_id, task_id);
create index observations_user_unit_idx on public.observations (user_id, unit_id);
create index recurring_requirements_user_unit_idx on public.recurring_requirements (user_id, unit_id);
create index study_sessions_task_id_idx on public.study_sessions (task_id);
create index study_sessions_user_unit_idx on public.study_sessions (user_id, unit_id);
create index tasks_user_recurring_requirement_idx on public.tasks (user_id, recurring_requirement_id);
create index tasks_user_unit_idx on public.tasks (user_id, unit_id);
create index timetable_entries_user_unit_idx on public.timetable_entries (user_id, unit_id);
create index unit_relationships_user_to_unit_idx on public.unit_relationships (user_id, to_unit_id);
create index unit_state_history_user_id_idx on public.unit_state_history (user_id);
create index unit_state_history_user_unit_idx on public.unit_state_history (user_id, unit_id);
create index units_academic_period_id_idx on public.units (academic_period_id);
