alter policy "Users can delete own academic events" on public.academic_events using ((select auth.uid()) = user_id);
alter policy "Users can insert own academic events" on public.academic_events with check ((select auth.uid()) = user_id);
alter policy "Users can update own academic events" on public.academic_events using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
alter policy "Users can view own academic events" on public.academic_events using ((select auth.uid()) = user_id);
alter policy "Users can delete own observations" on public.observations using ((select auth.uid()) = user_id);
alter policy "Users can insert own observations" on public.observations with check ((select auth.uid()) = user_id);
alter policy "Users can update own observations" on public.observations using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
alter policy "Users can view own observations" on public.observations using ((select auth.uid()) = user_id);
alter policy "Users can delete own recurring requirements" on public.recurring_requirements using ((select auth.uid()) = user_id);
alter policy "Users can insert own recurring requirements" on public.recurring_requirements with check ((select auth.uid()) = user_id);
alter policy "Users can update own recurring requirements" on public.recurring_requirements using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
alter policy "Users can view own recurring requirements" on public.recurring_requirements using ((select auth.uid()) = user_id);
alter policy "Users can delete own study sessions" on public.study_sessions using ((select auth.uid()) = user_id);
alter policy "Users can insert own study sessions" on public.study_sessions with check ((select auth.uid()) = user_id);
alter policy "Users can update own study sessions" on public.study_sessions using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
alter policy "Users can view own study sessions" on public.study_sessions using ((select auth.uid()) = user_id);
alter policy "Users can delete own timetable entries" on public.timetable_entries using ((select auth.uid()) = user_id);
alter policy "Users can insert own timetable entries" on public.timetable_entries with check ((select auth.uid()) = user_id);
alter policy "Users can update own timetable entries" on public.timetable_entries using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
alter policy "Users can view own timetable entries" on public.timetable_entries using ((select auth.uid()) = user_id);
alter policy "Users can delete own unit state history" on public.unit_state_history using ((select auth.uid()) = user_id);
alter policy "Users can insert own unit state history" on public.unit_state_history with check ((select auth.uid()) = user_id);
alter policy "Users can update own unit state history" on public.unit_state_history using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
alter policy "Users can view own unit state history" on public.unit_state_history using ((select auth.uid()) = user_id);
